### ISSUE TITLE
brew install ngless failed

### ISSUE THREAD

**Issue by jnesme** [luispedro/homebrew-ngless#1]
Dear Luis,

I'm trying to install ngless through homebrew and the install is failing with an error that seems very ngless specific rather than a homebrew hicup. I was wondering if you have any idea on how to fix this? I've attached the output I got from running brew install ngless

Sincerely,

Joseph.

`jnesme@Ponyo:~/Downloads/PacBio_HGAP4$ brew install ngless
==> Installing ngless from luispedro/ngless
==> Installing dependencies for luispedro/ngless/ngless: ghc, cabal-install
==> Installing luispedro/ngless/ngless dependency: ghc
==> Downloading https://homebrew.bintray.com/bottles/ghc-8.0.2.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/bb/bb2f8381ad551dfd540a2cad0db09b11f38a67090795b6b374d4bf596361e924?__gda__=exp=1498553000~hmac=0dbeaea15136050537962f35f35a655332
######################################################################## 100,0%
==> Pouring ghc-8.0.2.sierra.bottle.tar.gz
==> Using the sandbox
==> /usr/local/Cellar/ghc/8.0.2/bin/ghc-pkg recache
🍺  /usr/local/Cellar/ghc/8.0.2: 5,777 files, 1GB
==> Installing luispedro/ngless/ngless dependency: cabal-install
==> Downloading https://homebrew.bintray.com/bottles/cabal-install-1.24.0.2_3.sierra.bottle.tar.gz
==> Downloading from https://akamai.bintray.com/d2/d26d08a85d812cf89fd64e69b8ab3e28910c2d302ac661a9f572f6782bb06e80?__gda__=exp=1498553034~hmac=dbd75a9930589f482f675b39826489199d
######################################################################## 100,0%
==> Pouring cabal-install-1.24.0.2_3.sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/cabal-install/1.24.0.2_3: 7 files, 27.7MB
==> Installing luispedro/ngless/ngless
==> Downloading https://github.com/luispedro/ngless/archive/68e5a7782a0f33c5d443ffb9c610788bd21d7e53.zip
==> Downloading from https://codeload.github.com/luispedro/ngless/zip/68e5a7782a0f33c5d443ffb9c610788bd21d7e53
######################################################################## 100,0%
==> m4 NGLess.cabal.m4 > NGLess.cabal
==> cabal sandbox init
==> cabal update
==> cabal install --jobs=8 --max-backjumps=100000 --only-dependencies
==> cabal install --jobs=8 --max-backjumps=100000 --prefix=/usr/local/Cellar/ngless/0.0.0
Last 15 lines from /Users/jnesme/Library/Logs/Homebrew/ngless/05.cabal:
        ‘<|>’ (imported from Options.Applicative),
        ‘<$>’ (imported from Options.Applicative),
        ‘>>’ (imported from Prelude)

NGLess/CmdArgs.hs:137:42: error:
    • Variable not in scope:
        (<>) :: Mod f36 a33 -> Mod f35 a32 -> Mod FlagFields Bool
    • Perhaps you meant one of these:
        ‘<|>’ (imported from Options.Applicative),
        ‘<$>’ (imported from Options.Applicative),
        ‘>>’ (imported from Prelude)
cabal: Leaving directory '.'
cabal: Error: some packages failed to install:
NGLess-0.0.0 failed during the building phase. The exception was:
ExitFailure 1
`

**Comment by luispedro** [comment]
Thanks for the report (this is a _beta_ phase of ngless exactly to try and catch all these little issues). I'll put some time into this a bit later, but the first impression is that it's a GHC version issue and we probably need an extra few imports to support all versions of GHC or change how brew is building it so it's clearer.

**Comment by luispedro** [comment]
I just updated the version in this brew package, which may have fixed the issue. Unfortunately, I cannot test brew on this computer.

I will try to find a computer on which I can test, but if you have a minute in the meanwhile, let me know if it works now...

**Comment by jnesme** [comment]
I could install the updated version without any problem now, thanks a lot.

**Comment by luispedro** [comment]
Thanks for the info. Closing the issue...
